"""Date-based train / validation / test splitting for offline RL datasets.

The offline RL dataset is a single long trajectory of ``(s, a, r, s', done)``
transitions generated by rolling a behaviour policy through historical
market data. For an honest evaluation we must slice this trajectory by
*calendar date* so that:

* training uses only transitions whose state is observed on or before
  ``train_end``,
* validation uses only transitions inside ``[val_start, val_end]``,
* testing uses only transitions inside ``[test_start, test_end]``,
* the three windows are strictly time-ordered and non-overlapping.

All three splits share the same underlying arrays; we simply return the
index ranges that belong to each window. This is cheap and avoids any
chance of silently copying training data into a validation or test buffer.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

import numpy as np
import pandas as pd

__all__ = [
    "SplitConfig",
    "SplitIndices",
    "DEFAULT_SPLIT",
    "compute_split_indices",
    "assert_disjoint",
]


# ---------------------------------------------------------------------------
# Config + result types
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class SplitConfig:
    """Inclusive calendar-date boundaries for train / val / test."""

    train_start: str
    train_end: str
    val_start: str
    val_end: str
    test_start: str
    test_end: str

    def __post_init__(self) -> None:
        t_end = pd.Timestamp(self.train_end)
        v_start = pd.Timestamp(self.val_start)
        v_end = pd.Timestamp(self.val_end)
        te_start = pd.Timestamp(self.test_start)
        te_end = pd.Timestamp(self.test_end)
        if not (t_end < v_start):
            raise ValueError(
                f"train_end ({self.train_end}) must be strictly before "
                f"val_start ({self.val_start})."
            )
        if not (v_start <= v_end):
            raise ValueError(
                f"val_start ({self.val_start}) must be <= val_end ({self.val_end})."
            )
        if not (v_end < te_start):
            raise ValueError(
                f"val_end ({self.val_end}) must be strictly before "
                f"test_start ({self.test_start})."
            )
        if not (te_start <= te_end):
            raise ValueError(
                f"test_start ({self.test_start}) must be <= test_end "
                f"({self.test_end})."
            )


@dataclass(frozen=True)
class SplitIndices:
    """Integer index arrays identifying which rows of the dataset belong to
    each split. Indices are into the original (date-sorted) dataset arrays.
    """

    train: np.ndarray  # dtype=int64
    val: np.ndarray
    test: np.ndarray

    def summary(self) -> dict[str, int]:
        return {
            "train": int(self.train.size),
            "val": int(self.val.size),
            "test": int(self.test.size),
        }


# ---------------------------------------------------------------------------
# Project-wide default split (spec in CLAUDE.md)
# ---------------------------------------------------------------------------


DEFAULT_SPLIT = SplitConfig(
    train_start="2008-01-01",
    train_end="2020-12-31",
    val_start="2021-01-01",
    val_end="2021-12-31",
    test_start="2022-01-01",
    test_end="2026-03-31",
)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def compute_split_indices(
    dates: np.ndarray | pd.DatetimeIndex,
    cfg: SplitConfig = DEFAULT_SPLIT,
) -> SplitIndices:
    """Bucket each transition into train/val/test by its state date.

    Parameters
    ----------
    dates:
        1-D array of per-transition dates (the date on which ``state`` was
        observed and the action was taken). May be ``int64`` nanoseconds,
        ``datetime64``, or a ``DatetimeIndex``.
    cfg:
        Calendar boundaries. Defaults to :data:`DEFAULT_SPLIT`.

    Returns
    -------
    :class:`SplitIndices`. Any transition whose date falls outside all three
    windows is dropped. The three index arrays are non-overlapping.
    """
    dt = _to_datetime_index(dates)

    def _mask_between(start: str, end: str) -> np.ndarray:
        lo = pd.Timestamp(start)
        hi = pd.Timestamp(end)
        return np.asarray((dt >= lo) & (dt <= hi), dtype=bool)

    train_mask = _mask_between(cfg.train_start, cfg.train_end)
    val_mask = _mask_between(cfg.val_start, cfg.val_end)
    test_mask = _mask_between(cfg.test_start, cfg.test_end)

    train_idx = np.flatnonzero(train_mask).astype(np.int64)
    val_idx = np.flatnonzero(val_mask).astype(np.int64)
    test_idx = np.flatnonzero(test_mask).astype(np.int64)

    assert_disjoint(train_idx, val_idx, test_idx)

    for name, idx in (("train", train_idx), ("val", val_idx), ("test", test_idx)):
        if idx.size == 0:
            raise ValueError(
                f"Split '{name}' is empty given dataset spans "
                f"{dt.min().date()} → {dt.max().date()} and cfg={cfg!r}."
            )

    return SplitIndices(train=train_idx, val=val_idx, test=test_idx)


def assert_disjoint(*index_arrays: np.ndarray) -> None:
    """Assert that a collection of index arrays are pairwise disjoint."""
    all_indices = np.concatenate([np.asarray(a, dtype=np.int64) for a in index_arrays])
    if all_indices.size == 0:
        return
    unique = np.unique(all_indices)
    if unique.size != all_indices.size:
        raise AssertionError(
            "Split index arrays overlap — this would leak data between "
            "train/val/test. This should never happen with date-based splits."
        )


# ---------------------------------------------------------------------------
# Internals
# ---------------------------------------------------------------------------


def _to_datetime_index(dates: Any) -> pd.DatetimeIndex:
    if isinstance(dates, pd.DatetimeIndex):
        return dates
    arr = np.asarray(dates)
    if np.issubdtype(arr.dtype, np.datetime64):
        return pd.DatetimeIndex(arr)
    if np.issubdtype(arr.dtype, np.integer):
        # Stored as ns since epoch
        return pd.DatetimeIndex(pd.to_datetime(arr, unit="ns"))
    # Fallback: parse strings
    return pd.DatetimeIndex(pd.to_datetime(arr))
